name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-13
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 12"
          - "platform=tvOS Simulator,name=Apple TV"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme KeyCodes -destination "${{ matrix.destination }}" test | xcbeautify --renderer github-actions
